/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChoferRouteImport } from './routes/chofer'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellVehiculosRouteImport } from './routes/_shell.vehiculos'
import { Route as ShellRutasRouteImport } from './routes/_shell.rutas'
import { Route as ShellReportesRouteImport } from './routes/_shell.reportes'
import { Route as ShellPreparacionRouteImport } from './routes/_shell.preparacion'
import { Route as ShellPedidosRouteImport } from './routes/_shell.pedidos'
import { Route as ShellOperacionesRouteImport } from './routes/_shell.operaciones'
import { Route as ShellNuevoPedidoRouteImport } from './routes/_shell.nuevo-pedido'
import { Route as ShellIndicadoresRouteImport } from './routes/_shell.indicadores'
import { Route as ShellIncidenciasRouteImport } from './routes/_shell.incidencias'
import { Route as ShellConfiguracionRouteImport } from './routes/_shell.configuracion'
import { Route as ShellChoferesRouteImport } from './routes/_shell.choferes'
import { Route as ShellCalendarioRouteImport } from './routes/_shell.calendario'
import { Route as ShellArmadoDiaRouteImport } from './routes/_shell.armado-dia'

const ChoferRoute = ChoferRouteImport.update({
  id: '/chofer',
  path: '/chofer',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVehiculosRoute = ShellVehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRutasRoute = ShellRutasRouteImport.update({
  id: '/rutas',
  path: '/rutas',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportesRoute = ShellReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPreparacionRoute = ShellPreparacionRouteImport.update({
  id: '/preparacion',
  path: '/preparacion',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPedidosRoute = ShellPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOperacionesRoute = ShellOperacionesRouteImport.update({
  id: '/operaciones',
  path: '/operaciones',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNuevoPedidoRoute = ShellNuevoPedidoRouteImport.update({
  id: '/nuevo-pedido',
  path: '/nuevo-pedido',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIndicadoresRoute = ShellIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIncidenciasRoute = ShellIncidenciasRouteImport.update({
  id: '/incidencias',
  path: '/incidencias',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfiguracionRoute = ShellConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChoferesRoute = ShellChoferesRouteImport.update({
  id: '/choferes',
  path: '/choferes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCalendarioRoute = ShellCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => ShellRoute,
} as any)
const ShellArmadoDiaRoute = ShellArmadoDiaRouteImport.update({
  id: '/armado-dia',
  path: '/armado-dia',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/chofer': typeof ChoferRoute
  '/armado-dia': typeof ShellArmadoDiaRoute
  '/calendario': typeof ShellCalendarioRoute
  '/choferes': typeof ShellChoferesRoute
  '/configuracion': typeof ShellConfiguracionRoute
  '/incidencias': typeof ShellIncidenciasRoute
  '/indicadores': typeof ShellIndicadoresRoute
  '/nuevo-pedido': typeof ShellNuevoPedidoRoute
  '/operaciones': typeof ShellOperacionesRoute
  '/pedidos': typeof ShellPedidosRoute
  '/preparacion': typeof ShellPreparacionRoute
  '/reportes': typeof ShellReportesRoute
  '/rutas': typeof ShellRutasRoute
  '/vehiculos': typeof ShellVehiculosRoute
}
export interface FileRoutesByTo {
  '/chofer': typeof ChoferRoute
  '/armado-dia': typeof ShellArmadoDiaRoute
  '/calendario': typeof ShellCalendarioRoute
  '/choferes': typeof ShellChoferesRoute
  '/configuracion': typeof ShellConfiguracionRoute
  '/incidencias': typeof ShellIncidenciasRoute
  '/indicadores': typeof ShellIndicadoresRoute
  '/nuevo-pedido': typeof ShellNuevoPedidoRoute
  '/operaciones': typeof ShellOperacionesRoute
  '/pedidos': typeof ShellPedidosRoute
  '/preparacion': typeof ShellPreparacionRoute
  '/reportes': typeof ShellReportesRoute
  '/rutas': typeof ShellRutasRoute
  '/vehiculos': typeof ShellVehiculosRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/chofer': typeof ChoferRoute
  '/_shell/armado-dia': typeof ShellArmadoDiaRoute
  '/_shell/calendario': typeof ShellCalendarioRoute
  '/_shell/choferes': typeof ShellChoferesRoute
  '/_shell/configuracion': typeof ShellConfiguracionRoute
  '/_shell/incidencias': typeof ShellIncidenciasRoute
  '/_shell/indicadores': typeof ShellIndicadoresRoute
  '/_shell/nuevo-pedido': typeof ShellNuevoPedidoRoute
  '/_shell/operaciones': typeof ShellOperacionesRoute
  '/_shell/pedidos': typeof ShellPedidosRoute
  '/_shell/preparacion': typeof ShellPreparacionRoute
  '/_shell/reportes': typeof ShellReportesRoute
  '/_shell/rutas': typeof ShellRutasRoute
  '/_shell/vehiculos': typeof ShellVehiculosRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chofer'
    | '/armado-dia'
    | '/calendario'
    | '/choferes'
    | '/configuracion'
    | '/incidencias'
    | '/indicadores'
    | '/nuevo-pedido'
    | '/operaciones'
    | '/pedidos'
    | '/preparacion'
    | '/reportes'
    | '/rutas'
    | '/vehiculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chofer'
    | '/armado-dia'
    | '/calendario'
    | '/choferes'
    | '/configuracion'
    | '/incidencias'
    | '/indicadores'
    | '/nuevo-pedido'
    | '/operaciones'
    | '/pedidos'
    | '/preparacion'
    | '/reportes'
    | '/rutas'
    | '/vehiculos'
    | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/chofer'
    | '/_shell/armado-dia'
    | '/_shell/calendario'
    | '/_shell/choferes'
    | '/_shell/configuracion'
    | '/_shell/incidencias'
    | '/_shell/indicadores'
    | '/_shell/nuevo-pedido'
    | '/_shell/operaciones'
    | '/_shell/pedidos'
    | '/_shell/preparacion'
    | '/_shell/reportes'
    | '/_shell/rutas'
    | '/_shell/vehiculos'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  ChoferRoute: typeof ChoferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chofer': {
      id: '/chofer'
      path: '/chofer'
      fullPath: '/chofer'
      preLoaderRoute: typeof ChoferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vehiculos': {
      id: '/_shell/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof ShellVehiculosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/rutas': {
      id: '/_shell/rutas'
      path: '/rutas'
      fullPath: '/rutas'
      preLoaderRoute: typeof ShellRutasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reportes': {
      id: '/_shell/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ShellReportesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/preparacion': {
      id: '/_shell/preparacion'
      path: '/preparacion'
      fullPath: '/preparacion'
      preLoaderRoute: typeof ShellPreparacionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pedidos': {
      id: '/_shell/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof ShellPedidosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/operaciones': {
      id: '/_shell/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof ShellOperacionesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/nuevo-pedido': {
      id: '/_shell/nuevo-pedido'
      path: '/nuevo-pedido'
      fullPath: '/nuevo-pedido'
      preLoaderRoute: typeof ShellNuevoPedidoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/indicadores': {
      id: '/_shell/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof ShellIndicadoresRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/incidencias': {
      id: '/_shell/incidencias'
      path: '/incidencias'
      fullPath: '/incidencias'
      preLoaderRoute: typeof ShellIncidenciasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/configuracion': {
      id: '/_shell/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ShellConfiguracionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/choferes': {
      id: '/_shell/choferes'
      path: '/choferes'
      fullPath: '/choferes'
      preLoaderRoute: typeof ShellChoferesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/calendario': {
      id: '/_shell/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof ShellCalendarioRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/armado-dia': {
      id: '/_shell/armado-dia'
      path: '/armado-dia'
      fullPath: '/armado-dia'
      preLoaderRoute: typeof ShellArmadoDiaRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellArmadoDiaRoute: typeof ShellArmadoDiaRoute
  ShellCalendarioRoute: typeof ShellCalendarioRoute
  ShellChoferesRoute: typeof ShellChoferesRoute
  ShellConfiguracionRoute: typeof ShellConfiguracionRoute
  ShellIncidenciasRoute: typeof ShellIncidenciasRoute
  ShellIndicadoresRoute: typeof ShellIndicadoresRoute
  ShellNuevoPedidoRoute: typeof ShellNuevoPedidoRoute
  ShellOperacionesRoute: typeof ShellOperacionesRoute
  ShellPedidosRoute: typeof ShellPedidosRoute
  ShellPreparacionRoute: typeof ShellPreparacionRoute
  ShellReportesRoute: typeof ShellReportesRoute
  ShellRutasRoute: typeof ShellRutasRoute
  ShellVehiculosRoute: typeof ShellVehiculosRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellArmadoDiaRoute: ShellArmadoDiaRoute,
  ShellCalendarioRoute: ShellCalendarioRoute,
  ShellChoferesRoute: ShellChoferesRoute,
  ShellConfiguracionRoute: ShellConfiguracionRoute,
  ShellIncidenciasRoute: ShellIncidenciasRoute,
  ShellIndicadoresRoute: ShellIndicadoresRoute,
  ShellNuevoPedidoRoute: ShellNuevoPedidoRoute,
  ShellOperacionesRoute: ShellOperacionesRoute,
  ShellPedidosRoute: ShellPedidosRoute,
  ShellPreparacionRoute: ShellPreparacionRoute,
  ShellReportesRoute: ShellReportesRoute,
  ShellRutasRoute: ShellRutasRoute,
  ShellVehiculosRoute: ShellVehiculosRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  ChoferRoute: ChoferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
